[package]
name = "arcs-ibis"
version = "0.1.0"
edition = "2021"

[lib]
name = "ibis"
path = "src/lib.rs"

[dependencies]
crepe = { version = "0.1.5", path = "/home/jopra/google/crepe" }
paste = "1.0.6"
lazy_static = "1.4.0"
