[package]
name = "arcsjs-ibis"
version = "0.1.0"
edition = "2021"

[lib]
name = "ibis"
path = "src/lib.rs"

[features]
default = []
ancestors = [] # Support the tracking of ancestor solutions

[dependencies]
paste = "1.0.6"
crepe = { version = "0.1.5", path = "/home/jopra/google/crepe" }
lazy_static = "1.4.0"
ibis_macros = { path = "./ibis_macros" }

[dev_dependencies]
pretty_assertions = "1.0.0"
