name: Ibis

on:
  push:
    branches: [ main ]

defaults:
 run:
  working-directory: ./ibis

jobs:
  build_wasm:
    name: Build using ${{ matrix.os }} and WASM
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          pkg
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install wasm-pack toolchain
      run: cargo install wasm-pack
    - name: Build using wasm-pack
      run: wasm-pack build --target web --locked --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: ibis
        path: ibis/pkg/*
    # Run our deployment command
    - name: Set up a github identity
      run: git config --global user.email "test@example.com" && git config --global user.name "Github Actions"
    - name: Deploying the static website to origin/pages
      run: git checkout -b pages && git add -f pkg && git commit -m "Update pages" && git push origin/pages -f
