name: Ibis Pages

on:
  push:
    branches: [ main ]

defaults:
 run:
  working-directory: ./ibis

jobs:
  build_wasm:
    name: Build using ${{ matrix.os }} and WASM
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          pkg
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'
    - name: Build using wasm-pack
      run: wasm-pack build --target web --locked --release --verbose
    - name: Build docs using cargo doc
      run: cargo doc
    - name: Move docs to docs folder
      run: mv ./target/doc/* ./docs/
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: ibis
        path: ibis/pkg/*
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
